from services.notion import NotionService

notion = NotionService()

page_id = "2d722f89-689b-817c-9bcb-ef0a80654a0e"

sections = [
    ("h2", "How the System Works (High-Level Flow)"),
    ("paragraph", "This section explains the high-level flow by which new work is translated into clear, business-friendly documentation. It shows how information moves from change signals to published insights, helping leadership understand impact and make informed decisions."),
    ("bullet", "Detect change signals from code repository to trigger the documentation workflow"),
    ("bullet", "AI analyzes changes to draft the initial documentation"),
    ("bullet", "System refines draft with business input and aligns with goals"),
    ("bullet", "Publish and share the final documentation with stakeholders"),
    
    ("h2", "Impact & Results"),
    ("paragraph", "This section highlights the business outcomes generated by the documentation workflow: faster understanding of changes, clearer communication, stronger cross-team alignment, and reduced rework. These outcomes support better decisions and more efficient operations over time."),
    ("bullet", "Efficiency gains – Reduces time to understand changes and speeds decision-making"),
    ("bullet", "Improved accuracy – Documentation is clearer and reduces misinterpretations"),
    ("bullet", "Better collaboration – Improves cross-team alignment and reduces back-and-forth"),
    ("bullet", "Cost savings – Reduces overhead and rework costs"),
    
    ("h2", "Security, Compliance & Reliability"),
    ("paragraph", "All operations follow strict security protocols and validation rules to ensure safe, reliable performance. The system protects sensitive information and maintains data integrity throughout the documentation process."),
    ("bullet", "Secure access controls – Only authorized users can access and modify documentation"),
    ("bullet", "Data protection – All information is handled according to security best practices"),
    ("bullet", "Reliable operations – System validates all actions before execution"),
    
    ("h2", "Current Status"),
    ("bullet", "Active development with core features implemented and documented"),
    ("bullet", "Near-term readiness – Ready for stakeholder review and feedback; roadmap for enhancements in the next release"),
    ("paragraph", "Current status: Core features are implemented and documented. The project is actively being refined with feedback loops in place. Next, we will gather stakeholder input and begin the planned enhancements in the upcoming release."),
]

print("Adding missing sections to Notion page...")
for block_type, text in sections:
    result = notion.create_blocks(f"{block_type}|{text}")
    if result.get("success"):
        block = result.get("block") if "block" in result else result.get("blocks")
        if block:
            import json
            block_json = json.dumps(block)
            append_result = notion.append_blocks(f"{page_id}|{block_json}")
            if append_result.get("success"):
                print(f"✓ Added {block_type}: {text[:50]}...")
            else:
                print(f"✗ Failed to append {block_type}: {append_result.get('error')}")
        else:
            print(f"✗ No block returned for {block_type}")
    else:
        print(f"✗ Failed to create {block_type}: {result.get('error')}")

print("\nDone! Check your Notion page.")
